version: "3.8"

services:
  element-web:
    image: vectorim/element-web:v1.11.96
    container_name: element-web
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    ports:
      - "8081:80"
