version: "3.8"

services:
  synapse:
    image: ghcr.io/element-hq/synapse:1.148.0
    container_name: synapse
    restart: unless-stopped
    ports:
      - "127.0.0.1:8008:8008"
    volumes:
      - ./data:/data
